### ISSUE TITLE
Model conversion fails

### ISSUE THREAD

**Issue by lukaszsobala** [happyme531/RK3588-stable-diffusion-GPU#1]
Here is the command:
`python RK3588-stable-diffusion-GPU/convert_model_from_pth_safetensors.py --checkpoint_path stable-diffusion-v1-5/v1-5-pruned-emaonly.safetensors --dump_path ./stable-diffusion-v1-5/ --from_safetensors --original_config_file stable-diffusion-v1-5/v1-inference.yaml`

And the output:
```
Traceback (most recent call last):                                                                  File "/home/[redacted]/Software/RK3588-stable-diffusion-GPU/convert_model_from_pth_safetensors.py", line 160, in <module>
    pipe = download_from_original_stable_diffusion_ckpt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                            File "/home/[redacted]/miniconda3/lib/python3.11/site-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1329, in download_from_original_stable_diffusion_ckpt
    and "cond_stage_config" in original_config["model"]["params"]
                               ~~~~~~~~~~~~~~~^^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

Any ideas?

**Comment by lukaszsobala** [comment]
I tried using diffusers 0.25.1 and it worked? With 0.26.3 (what I was using previously) it failed.

Why did this happen?

**Comment by happyme531** [comment]
The conversion script is taken from https://github.com/huggingface/diffusers/blob/main/scripts/convert_original_stable_diffusion_to_diffusers.py
Open a issue there if you like.
